VERSION="2.0.0"

NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

ACCOUNTS=[
"GCX2VYFJNEAGQGC7U2WKKHVEI5Y5NMVDUIH2PCBAL4V72ZKM2EJUNDFR"
]

SIGNING_KEY="GCX2VYFJNEAGQGC7U2WKKHVEI5Y5NMVDUIH2PCBAL4V72ZKM2EJUNDFR"